# snakeRules
IS_ORACLE = False
MOVE_PENALTY = 1
MICE_TO_WIN = 200
MOUSE_REWARD_MULTIPLIER = 1

# game
DEFAULT_DIMENSONS = (20, 20)
DEFAULT_NUM_MICE = 20
DEFAULT_NUM_GAMES = 50
DISPLAY = True
SLEEP_TIME = 0